export enum PermissionCode {
  // Revenue / Land Records
  VIEW_LAND = 'VIEW_LAND',
  CREATE_LAND = 'CREATE_LAND',
  UPDATE_LAND = 'UPDATE_LAND',
  VIEW_GIS = 'VIEW_GIS',
  VERIFY_OWNERSHIP = 'VERIFY_OWNERSHIP',
  APPROVE_MUTATION = 'APPROVE_MUTATION',
  VIEW_TRANSFER_HISTORY = 'VIEW_TRANSFER_HISTORY',
  VIEW_DOCUMENTS = 'VIEW_DOCUMENTS',

  // Survey & Land Records
  CREATE_SURVEY = 'CREATE_SURVEY',
  UPDATE_SURVEY = 'UPDATE_SURVEY',
  UPDATE_PROPOSED_BOUNDARY = 'UPDATE_PROPOSED_BOUNDARY',
  UPLOAD_SURVEY_DOCUMENT = 'UPLOAD_SURVEY_DOCUMENT',
  SUBMIT_SURVEY_VERIFICATION = 'SUBMIT_SURVEY_VERIFICATION',

  // Registration & Stamps
  VIEW_OWNERSHIP = 'VIEW_OWNERSHIP',
  VERIFY_REGISTRATION = 'VERIFY_REGISTRATION',
  CREATE_TRANSFER = 'CREATE_TRANSFER',
  UPLOAD_REGISTRATION_DOCUMENT = 'UPLOAD_REGISTRATION_DOCUMENT',

  // Municipality / Local Body
  VIEW_PROPERTY = 'VIEW_PROPERTY',
  VERIFY_PROPERTY = 'VERIFY_PROPERTY',
  VERIFY_TAX = 'VERIFY_TAX',
  UPLOAD_PROPERTY_DOCUMENT = 'UPLOAD_PROPERTY_DOCUMENT',

  // Super Admin / Governance
  MANAGE_DEPARTMENTS = 'MANAGE_DEPARTMENTS',
  MANAGE_DESIGNATIONS = 'MANAGE_DESIGNATIONS',
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
  MANAGE_SCOPE = 'MANAGE_SCOPE',
  VIEW_ALL_LANDS = 'VIEW_ALL_LANDS',
  VIEW_ALL_VERIFICATIONS = 'VIEW_ALL_VERIFICATIONS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
  VIEW_DIGITAL_TWINS = 'VIEW_DIGITAL_TWINS',
}
