export enum LandStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  REQUIRES_SURVEY = 'REQUIRES_SURVEY',
  SURVEY_IN_REVIEW = 'SURVEY_IN_REVIEW',
  SURVEY_VERIFIED = 'SURVEY_VERIFIED',
  REQUIRES_REGISTRATION_VERIFICATION = 'REQUIRES_REGISTRATION_VERIFICATION',
  REGISTRATION_IN_REVIEW = 'REGISTRATION_IN_REVIEW',
  REGISTRATION_VERIFIED = 'REGISTRATION_VERIFIED',
  REQUIRES_MUNICIPAL_VERIFICATION = 'REQUIRES_MUNICIPAL_VERIFICATION',
  MUNICIPAL_IN_REVIEW = 'MUNICIPAL_IN_REVIEW',
  MUNICIPAL_VERIFIED = 'MUNICIPAL_VERIFIED',
  LAND_VERIFIED = 'LAND_VERIFIED',
  REQUIRES_CORRECTION = 'REQUIRES_CORRECTION',
  REJECTED = 'REJECTED',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  REQUIRES_CORRECTION = 'REQUIRES_CORRECTION',
}

export enum TransferType {
  SALE = 'SALE',
  GIFT = 'GIFT',
  INHERITANCE = 'INHERITANCE',
  PARTITION = 'PARTITION',
  COURT_ORDER = 'COURT_ORDER',
  GOVT_ALLOTMENT = 'GOVT_ALLOTMENT',
  OTHER = 'OTHER',
}

export enum LandType {
  AGRICULTURAL = 'AGRICULTURAL',
  COMMERCIAL = 'COMMERCIAL',
  RESIDENTIAL = 'RESIDENTIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  GOVERNMENT = 'GOVERNMENT',
  FOREST = 'FOREST',
}

export enum OwnershipType {
  INDIVIDUAL = 'INDIVIDUAL',
  JOINT = 'JOINT',
  CORPORATE = 'CORPORATE',
  TRUST = 'TRUST',
  GOVERNMENT = 'GOVERNMENT',
}

export enum DepartmentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum DesignationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum OfficerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum DocumentType {
  SALE_DEED = 'SALE_DEED',
  PATTA_CHITTA = 'PATTA_CHITTA',
  EXTRACT_7_12 = 'EXTRACT_7_12',
  SURVEY_FMB = 'SURVEY_FMB',
  ENCUMBRANCE_CERTIFICATE = 'ENCUMBRANCE_CERTIFICATE',
  TAX_RECEIPT = 'TAX_RECEIPT',
  MUTATION_ORDER = 'MUTATION_ORDER',
  SURVEY_DOCUMENT = 'SURVEY_DOCUMENT',
  REGISTRATION_DOCUMENT = 'REGISTRATION_DOCUMENT',
  PROPERTY_DOCUMENT = 'PROPERTY_DOCUMENT',
}
